# Site settings
title: Set Sail for the Moon
email: moonstrike1024@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://moonstrike.github.io" # the base hostname & protocol for your site

# Sidebar settings
description: >
  Search engines, Go, Ansible, Hadoop, Spark, Storm, Kafka, and so on...

# Social icons
#facebook: username
#linkedin: username
github: MoonStrike
#deviantart: username
#codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
